# Generated by Django 5.2.5 on 2025-08-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=15)),
                ('fuel', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('inicial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.client')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.vehicle')),
            ],
        ),
    ]
